services:
  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend.onrender.com
